apiVersion: v1
kind: Service
metadata:
    name: "logitrainaks-2f73"
    labels:
        app: "logitrainaks-2f73"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "logitrainaks-2f73"