on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: logitrainregistry.azurecr.io
        username: ${{ secrets.acr_logitrainregistry_username }}
        password: ${{ secrets.acr_logitrainregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t logitrainregistry.azurecr.io/logitrainaks:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push logitrainregistry.azurecr.io/logitrainaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_logitrainaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep logitrainaksa1f6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace logitrainaksa1f6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: logitrainaksa1f6
        container-registry-url: logitrainregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_logitrainregistry_username }}
        container-registry-password: ${{ secrets.acr_logitrainregistry_password }}
        secret-name: logitrainaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: logitrainaksa1f6
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          logitrainregistry.azurecr.io/logitrainaks:${{ github.sha }}
        imagepullsecrets: |
          logitrainaksdockerauth
